image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_BUILDKIT: 1

stages:
  - build

build-and-push:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
  script:
    - docker buildx build --push 
      --platform linux/amd64,linux/arm64 
      -t $CI_REGISTRY_IMAGE:latest 
      .
  rules:
    - if: $CI_COMMIT_BRANCH == "main"