services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASS=secret
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  mongo-data: