version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/guirgouveia/google-sso-golang:latest
    container_name: auth
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  mongo-data:
